# **1. Data Types and Data Structures**

**Basic Variable Types**

In [ ]:
my_string1 = 'Welcome to'
my_string2 = "QuantConnect"
print(my_string1 + ' ' + my_string2)

Welcome to QuantConnect


In [ ]:
my_string1 = 'Hola, bienvenido a'
my_string2 = "el curso de QuantConnect"
print(my_string1 + ' ' + my_string2)

Bienvenido a el curso de QuantConnect


In [ ]:
my_int = 10
print(my_int)

10


In [ ]:
my_int = 23
print(my_int)

23


In [ ]:
print(type(my_int))

<class 'int'>


In [ ]:
print(type(my_int))

<class 'int'>


In [ ]:
my_string = "100"
print(type(my_string))

<class 'str'>


In [ ]:
my_string = "325"
print(type(my_string))

<class 'str'>


In [ ]:
my_int = int(my_string)
print(type(my_int))

<class 'int'>


In [ ]:
my_int = int(my_string)
print(type(my_int))

<class 'int'>


In [ ]:
my_float = 1.0
print(type(my_float))

<class 'float'>


In [ ]:
my_float = 5.1
print(type(my_float))

<class 'float'>


In [ ]:
my_int = 1
print(type(my_int))

<class 'int'>


In [ ]:
my_int = 7
print(type(my_int))

<class 'int'>


In [ ]:
my_string = "100"
my_float = float(my_string)
print(type(my_float))

<class 'float'>


In [ ]:
my_string = "270"
my_float = float(my_string)
print(type(my_float))

<class 'float'>


In [ ]:
my_bool = False
print(my_bool)

False


In [ ]:
my_bool = False
print(my_bool)

False


In [ ]:
print(type(my_bool))

<class 'bool'>


In [ ]:
print(type(my_bool))

<class 'bool'>


**Basic Math Operations**

In [ ]:
print("Addition ", 1+1)
print("Subtraction ", 5-2)
print("Multiplication ", 2*3)
print("Division", 10/2)
print("exponent", 2**3)

Addition  2
Subtraction  3
Multiplication  6
Division 5.0
exponent 8


In [ ]:
print("Addition ", 4+2)
print("Subtraction ", 7-8)
print("Multiplication ", 5*3)
print("Division", 24/6)
print("exponent", 2**2)

Addition  6
Subtraction  -1
Multiplication  15
Division 4.0
exponent 4


**Data Collections**

In [ ]:
my_list = ['Quant', 'Connect', 1,2,3]
print(my_list)

['Quant', 'Connect', 1, 2, 3]


In [ ]:
my_list = [1.5, 24, "Andrea",2,"Camilo",5]
print(my_list)

[1.5, 24, 'Andrea', 2, 'Camilo', 5]


In [ ]:
my_list = ['Quant', 'Connect', 1,2,3]
print(len(my_list))

5


In [ ]:
print(len(my_list))

6


In [ ]:
print(my_list[0])

Quant


In [ ]:
print(my_list[0])

1.5


In [ ]:
print(my_list[len(my_list) - 1])

3


In [ ]:
print(my_list[len(my_list) - 1])

5


In [ ]:
my_list = ['Quant','Connect',1,2,3]
my_list[2] = 'go'
print(my_list)

['Quant', 'Connect', 'go', 2, 3]


In [ ]:
my_list = [1.5, 24, "Andrea",2,"Camilo",5]
my_list[2] = 'Gato'
print(my_list)

[1.5, 24, 'Gato', 2, 'Camilo', 5]


In [ ]:
my_list = ['Quant','Connect',1,2,3]
print(my_list[1:3])

['Connect', 1]


In [ ]:
my_list = [1.5, 24, "Andrea",2,"Camilo",5]
print(my_list[1:3])

[24, 'Andrea']


In [ ]:
print(my_list[1:])

['Connect', 1, 2, 3]


In [ ]:
print(my_list[1:])

[24, 'Andrea', 2, 'Camilo', 5]


In [ ]:
print(my_list[:3])

['Quant', 'Connect', 1]


In [ ]:
print(my_list[:3])

[1.5, 24, 'Andrea']


In [ ]:
my_list = ['Hello', 'Quant']
my_list.append('Hello')
print(my_list)

['Hello', 'Quant', 'Hello']


In [ ]:
my_list = ['Hola', 'Buenos días']
my_list.append('Buenas tardes')
print(my_list)

['Hola', 'Buenos días', 'Buenas tardes']


In [ ]:
my_list.remove('Hello')
print(my_list)

['Quant', 'Hello']


In [ ]:
my_list.remove('Buenas tardes')
print(my_list)

['Hola', 'Buenos días']


In [ ]:
my_tuple = ('Welcome','to','QuantConnect')

In [ ]:
my_tuple = ('Introducción','al curso','QuantConnect')

In [ ]:
my_tuple = ('Welcome','to','QuantConnect')
print(my_tuple[1:])

('to', 'QuantConnect')


In [ ]:
my_tuple = ('Introducción','al curso','QuantConnect')
print(my_tuple[1:])

('al curso', 'QuantConnect')


In [ ]:
stock_list = ['AAPL','GOOG','IBM','AAPL','IBM','FB','F','GOOG']
stock_set = set(stock_list)
print(stock_set)

{'AAPL', 'FB', 'F', 'IBM', 'GOOG'}


In [ ]:
country_list = ['CO','MX','AG','RD','GM','ES','BR']
country_set = set(country_list)
print(country_set)

{'RD', 'BR', 'MX', 'ES', 'GM', 'AG', 'CO'}


In [ ]:
my_dic = {'AAPL': 'Apple', 'FB': 'FaceBook', 'GOOG': 'Alphabet'}

In [ ]:
print(my_dic['GOOG'])

Alphabet Company


In [ ]:
my_dic['GOOG'] = 'Alphabet Company'
print(my_dic['GOOG'])

Alphabet Company


In [ ]:
my_dic = {'PRR': 'Perro', 'CAB': 'Caballo', 'GLL': 'Gallina'}
print(my_dic['CAB'])

Caballo


In [ ]:
my_dic['PRR'] = 'Perro labrador'
print(my_dic['PRR'])

Perro labrador


In [ ]:
print(my_dic.keys())

dict_keys(['AAPL', 'FB', 'GOOG'])


In [ ]:
print(my_dic.keys())

dict_keys(['PRR', 'CAB', 'GLL'])


**Common String Operations**

In [ ]:
my_str = 'Welcome to QuantConnect'
print(my_str[8:])

to QuantConnect


In [ ]:
my_str = 'Hola, esta es una nueva forma de aprendizaje'
print(my_str[8:])

ta es una nueva forma de aprendizaje


In [ ]:
print("Counting the number of e's in this sentence".count('e'))

6


In [ ]:
print("Counting the number of i's in this sentence".count('i'))

4


In [ ]:
print('The first time e appears in this sentence'.find('e'))

2


In [ ]:
print('The first time e appears in this sentence'.find('h'))

1


In [ ]:
print('all the a in this sentence now becomes e'.replace('a','e'))

ell the e in this sentence now becomes e


In [ ]:
print('all the o in this sentence now becomes u'.replace('o','u'))

all the u in this sentence nuw becumes u


In [ ]:
Time = '2016-04-01 09:43:00'
splited_list = Time.split(' ')
date = splited_list[0]
time = splited_list[1]
print(date, time)

2016-04-01 09:43:00


In [ ]:
Time = '2021-12-10 10:14:00'
splited_list = Time.split(' ')
date = splited_list[0]
time = splited_list[1]
print(date, time)

2021-12-10 10:14:00


In [ ]:
hour = time.split(':')[0]
print(hour)

09


In [ ]:
hour = time.split(':')[0]
print(hour)

10


In [ ]:
my_time = 'Hour: {}, Minute: {}'.format(9, 43)
print(my_time)

Hour: 9, Minute: 43


In [ ]:
my_time = 'Hour: {}, Minute: {}'.format(12, 3)
print(my_time)

Hour: 12, Minute: 3


In [ ]:
print('pi is %f' % 3.14)

pi is 3.140000


In [ ]:
print('e is %f' % 2.718)

e is 2.718000


In [ ]:
print('%s to %s' % ('Welcome', 'QuantConnect'))

Welcome to QuantConnect


In [ ]:
print('%s a %s' % ('Bienvenido', 'python'))

Bienvenido a python


# **2. Logical Operations and Loops**

**Logical Operations**

In [ ]:
print(1 == 0)    # 1 equals 0
print(1 == 1)    # 1 equals 1
print(1 != 0)    # 1 is not equal to 0
print(5 >= 5)    # 5 is greater than or equal to 5
print(5 >= 6)    # 5 is greater than or equal to 6

False
True
True
True
False


In [ ]:
print(7 == 7)    # 7 equals 7
print(21 == 22)  # 21 equals 22
print(0 != 0)    # 0 is not equal to 0
print(9 >= 9)    # 9 is greater than or equal to 9
print(1 >= 20)   # 1 is greater than or equal to 20

True
False
False
True
False


In [ ]:
print(2 > 1 and 3 > 2)
print(2 > 1 and 3 < 2)
print(2 > 1 or  3 < 2)
print(2 < 1 and 3 < 2)

True
False
True
False


In [ ]:
print(4 > 6 and 7 > 2)
print(5 > 3 and 4 < 7)
print(1 > 0 or  -3 < 2)
print(-5 < 1 and -9 < -10)

False
True
True
False


In [ ]:
print (3 > 2 or 1 < 3) and (1!=3 and 4>3) and not ( 3 < 2 or 1 < 3 and (1!=3 and 4>3))
print(3 > 2 or 1 < 3 and (1!=3 and 4>3) and not ( 3 < 2 or 1 < 3 and (1!=3 and 4>3)))

True
True


In [ ]:
print (4 > 3 or 2 < 6) and (9!=1 and 6>3) and not ( 3 < 7 or 1 < 8 and (0!=1 and 4>-3))
print (6 > 7 or 5 < 4 and (3!=3 and 4>-7) and not ( -3 < 2 or 6 < 3 and (5!=3 and 2>3)))

True
False


**If Statement**

In [ ]:
i = 0
if i == 0: print('i == 0 is True')

i == 0 is True


In [ ]:
i = 21
if i == 21: print('i == 21 is True')

i == 21 is True


In [ ]:
p = 1 > 0
q = 2 > 3
if p and q:
    print('p and q is true')
elif p and not q:
    print('q is false')
elif q and not p:
    print('p is false')
else:
    print('None of p and q is true')

q is false


In [ ]:
p = 6 > 0
q = 7 > 4
if p and q:
    print('p and q is true')
elif p and not q:
    print('q is false')
elif q and not p:
    print('p is false')
else:
    print('None of p and q is true')

p and q is true


**Loop Structure**

In [ ]:
i = 0
while i < 5:
    print(i)
    i += 1

0
1
2
3
4


In [ ]:
i = 2
while i < 9:
    print(i)
    i += 1

2
3
4
5
6
7
8


In [ ]:
for x in [1,2,3,4,5]: print(x)

In [ ]:
for x in [0,1,2,3,4,5,6,7,8,9]: print(x)

0
1
2
3
4
5
6
7
8
9


In [ ]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM']
new_list = []
for stock in stocks:
    if stock not in selected:
        new_list.append(stock)
print(new_list)

['GOOG', 'FB', 'F', 'V', 'G', 'GE']


In [ ]:
countries = ['CO','MX','AG','RD','GM','ES','BR']
selected = ['CO','ES']
new_list = []
for country in countries:
    if country not in selected:
        new_list.append(country)
print(new_list)

['MX', 'AG', 'RD', 'GM', 'BR']


In [ ]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    print(stock)
    if stock == 'FB': break

AAPL
GOOG
IBM
FB


In [ ]:
countries = ['CO','MX','AG','RD','GM','ES','BR']
for country in countries:
    print(country)
    if country == 'GM': break

CO
MX
AG
RD
GM


In [ ]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    if stock == 'FB': continue
    print(stock)

AAPL
GOOG
IBM
F
V
G
GE


In [ ]:
countries = ['CO','MX','AG','RD','GM','ES','BR']
for country in countries:
    if country == 'GM': continue
    print(country)

CO
MX
AG
RD
ES
BR


**List Comprehension**

In [ ]:
squares = []
for i in [1,2,3,4,5]:
    squares.append(i**2)
print(squares)

[1, 4, 9, 16, 25]


In [ ]:
sqrts = []
for i in [4,9,16,25,36]:
    sqrts.append(i**(1/2))
print(sqrts)

[2.0, 3.0, 4.0, 5.0, 6.0]


In [ ]:
foo = [1,2,3,4,5]
squares = [x**2 for x in foo]
print(squares)

[1, 4, 9, 16, 25]


In [ ]:
elements = [2,4,6,8,10]
squares = [x**2 for x in elements]
print(squares)

[4, 16, 36, 64, 100]


In [ ]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM']
new_list = [x for x in stocks if x not in selected]
print(new_list)

['GOOG', 'FB', 'F', 'V', 'G', 'GE']


In [ ]:
countries = ['CO','MX','AG','RD','GM','ES','BR']
selected = ['CO','ES']
new_list = [x for x in countries if x not in selected]
print(new_list)

['MX', 'AG', 'RD', 'GM', 'BR']


In [ ]:
print([(x, y) for x in [1,2,3] for y in [3,1,4] if x != y])
print([str(x) + ' vs ' + str(y) for x in ['AAPL','GOOG','IBM','FB']
                                for y in ['F','V','G','GE'] if x != y])

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]
['AAPL vs F', 'AAPL vs V', 'AAPL vs G', 'AAPL vs GE', 'GOOG vs F', 'GOOG vs V', 'GOOG vs G', 'GOOG vs GE', 'IBM vs F', 'IBM vs V', 'IBM vs G', 'IBM vs GE', 'FB vs F', 'FB vs V', 'FB vs G', 'FB vs GE']


In [ ]:
print([(x, y) for x in [1,2,3] for y in [3,1,4] if x != y])
print([str(x) + ' vs ' + str(y) for x in ['CO','MX','AG','RD','GM','ES','BR']
                                for y in ['C','M','A','R'] if x != y])

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]
['CO vs C', 'CO vs M', 'CO vs A', 'CO vs R', 'MX vs C', 'MX vs M', 'MX vs A', 'MX vs R', 'AG vs C', 'AG vs M', 'AG vs A', 'AG vs R', 'RD vs C', 'RD vs M', 'RD vs A', 'RD vs R', 'GM vs C', 'GM vs M', 'GM vs A', 'GM vs R', 'ES vs C', 'ES vs M', 'ES vs A', 'ES vs R', 'BR vs C', 'BR vs M', 'BR vs A', 'BR vs R']


## **3. Functions and Objective-Oriented Programming**

**Functions**

In [ ]:
def product(x,y):
    return x*y
print(product(2,3))

6


In [ ]:
def product(x,y):
    return x*y
print(product(6,-1))

-6


In [ ]:
print(product(10,10))

100


In [ ]:
def say_hi():
    print("Welcome to QuantConnect")
say_hi()

Welcome to QuantConnect


In [ ]:
def saludo():
    print("Buenos días, bienvenido a python")
saludo()

Buenos días, bienvenido a python


**Built-in Function**

In [ ]:
print(range(10))

range(0, 10)


In [ ]:
list(*[range(10)])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
print(range(1, 11))

range(1, 11)


In [ ]:
list(*[range(1, 11)])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
print(range(1, 11, 2))

range(1, 11, 2)


In [ ]:
list(*[range(1, 11, 2)])

[1, 3, 5, 7, 9]

In [ ]:
tickers = ['AAPL', 'GOOGL', 'IBM', 'FB', 'F', 'V', 'G', 'GE']
print("The number of tickers is {}".format(len(tickers)))
for k in range(len(tickers)):
    print(k + 1, tickers[k])

The number of tickers is 8
1 AAPL
2 GOOGL
3 IBM
4 FB
5 F
6 V
7 G
8 GE


In [ ]:
countries = ['CO','MX','AG','RD','GM','ES','BR']
print("The number of countries is {}".format(len(countries)))
for k in range(len(countries)):
    print(k + 1, countries[k])

The number of countries is 7
1 CO
2 MX
3 AG
4 RD
5 GM
6 ES
7 BR


In [ ]:
tickers = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
print(list(map(len,tickers)))

[4, 4, 3, 2, 1, 1, 1, 2]


In [ ]:
countries = ['CO','MX','AG','RD','GM','ES','BR']
print(list(map(len,countries)))

[2, 2, 2, 2, 2, 2, 2]


In [ ]:
list(map(lambda x: x**2, range(10)))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
list(map(lambda x: x**3, range(12)))

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000, 1331]

In [ ]:
list(map(lambda x, y: x+y, [1,2,3,4,5], [5,4,3,2,1]))

[6, 6, 6, 6, 6]

In [ ]:
list(map(lambda x, y: x+y, [2,3,7,-4,12], [6,2,0,2,0]))

[8, 5, 7, -2, 12]

In [ ]:
sorted([5,2,3,4,1])

[1, 2, 3, 4, 5]

In [ ]:
sorted([5,2,3,8,4,1,6,7])

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
sorted(price_list, key = lambda x: x[1])

[('MSFT', 69),
 ('WMT', 75.32),
 ('AAPL', 144.09),
 ('FB', 150),
 ('GOOGL', 911.71)]

In [ ]:
PIB_list = [('CO', 144.09), ('ES', 911.71), ('MX', 69), ('BR', 150), ('RD', 75.32)]
sorted(PIB_list, key = lambda x: x[1])

[('MX', 69), ('RD', 75.32), ('CO', 144.09), ('BR', 150), ('ES', 911.71)]

In [ ]:
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
sorted(price_list, key = lambda x: x[1], reverse = True)

[('GOOGL', 911.71),
 ('FB', 150),
 ('AAPL', 144.09),
 ('WMT', 75.32),
 ('MSFT', 69)]

In [ ]:
PIB_list = [('CO', 144.09), ('ES', 911.71), ('MX', 69), ('BR', 150), ('RD', 75.32)]
sorted(PIB_list, key = lambda x: x[1], reverse = True)

[('ES', 911.71), ('BR', 150), ('CO', 144.09), ('RD', 75.32), ('MX', 69)]

In [ ]:
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
price_list.sort(key = lambda x: x[1])
print(price_list)

[('MSFT', 69), ('WMT', 75.32), ('AAPL', 144.09), ('FB', 150), ('GOOGL', 911.71)]


In [ ]:
PIB_list = [('CO', 144.09), ('ES', 911.71), ('MX', 69), ('BR', 150), ('RD', 75.32)]
PIB_list.sort(key = lambda x: x[1])
print(PIB_list)

[('MX', 69), ('RD', 75.32), ('CO', 144.09), ('BR', 150), ('ES', 911.71)]


**Object-Oriented Programming**

In [ ]:
class Stock:
    def __init__(self, ticker, open, close, volume):
        self.ticker = ticker
        self.open = open
        self.close = close
        self.volume = volume
        self.rate_return = float(close)/open - 1

    def update(self, open, close):
        self.open = open
        self.close = close
        self.rate_return = float(self.close)/self.open - 1

    def print_return(self):
        print(self.rate_return)

In [ ]:
class Stock:
    def __init__(self, ticker, open, close, volume):
        self.ticker = ticker
        self.open = open
        self.close = close
        self.volume = volume
        self.rate_return = float(close)/open - 1

    def update(self, open, close):
        self.open = open
        self.close = close
        self.rate_return = float(self.close)/self.open - 1

    def print_return(self):
        print(self.rate_return)

In [ ]:
apple  = Stock('AAPL', 143.69, 144.09, 20109375)
google = Stock('GOOGL', 898.7, 911.7, 1561616)

In [ ]:
carrot  = Stock('CARR', 163.15, 44.18, 2348970)
milk = Stock('MILK', 788.1, 523.07, 1267989)

In [ ]:
apple.ticker

'AAPL'

In [ ]:
carrot.ticker

'CARR'

In [ ]:
google.print_return()

0.014465338822744034


In [ ]:
milk.print_return()

-0.33628981093769816


In [ ]:
google.update(912.8,913.4)
google.print_return()

0.0006573181419806673


In [ ]:
milk.update(922.7,925.6)
milk.print_return()

0.0031429500379320796


In [ ]:
apple.ceo = 'Tim Cook'
apple.ceo

'Tim Cook'

In [ ]:
milk.maker = 'Colanta'
milk.maker

'Colanta'

In [ ]:
dir(apple)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'ceo',
 'close',
 'open',
 'print_return',
 'rate_return',
 'ticker',
 'update',
 'volume']

In [ ]:
dir(carrot)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'close',
 'open',
 'print_return',
 'rate_return',
 'ticker',
 'update',
 'volume']

In [ ]:
class Child(Stock):
    def __init__(self, name):
        self.name = name

In [ ]:
class Egg(Stock):
    def __init__(self, name):
        self.name = name

In [ ]:
aa = Child('AA')
print(aa.name)

AA


In [ ]:
he = Egg('HappyEgg')
print(he.name)

HappyEgg


In [ ]:
aa.update(100, 102)
print(aa.open)
print(aa.close)
print(aa.print_return())

100
102
0.020000000000000018
None


In [ ]:
he.update(110, 202)
print(he.open)
print(he.close)
print(he.print_return())

## **4. NumPy and Basic Pandas**

**NumPy**

In [ ]:
import numpy as np

In [ ]:
price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
print(price_array, type(price_array))

[143.73 145.83 143.68 144.02 143.5  142.62] <class 'numpy.ndarray'>


In [ ]:
price_list = [261.33, 121.76, 121.98, 150.19, 149.99, 140.12]
price_array = np.array(price_list)
print(price_array, type(price_array))

[261.33 121.76 121.98 150.19 149.99 140.12] <class 'numpy.ndarray'>


In [ ]:
Ar = np.array([[1,3], [2,4]])
print(Ar, type(Ar))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>


In [ ]:
Array = np.array([[1,3], [2,4]])
print(Array, type(Array))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>


In [ ]:
print(Ar.shape)

(2, 2)


In [ ]:
print(Array.shape)

(2, 2)


In [ ]:
print(Ar[0])

[1 3]


In [ ]:
print(Array[0])

[1 3]


In [ ]:
print(Ar[1])

[2 4]


In [ ]:
print(Array[1])

[2 4]


In [ ]:
print('First column:', Ar[:,0])

First column: [1 2]


In [ ]:
print('First column:', Array[:,0])

First column: [1 2]


In [ ]:
print('Second column:', Ar[:,1])

Second column: [3 4]


In [ ]:
print('Second column:', Array[:,1])

Second column: [3 4]


In [ ]:
np.log(price_array)

array([5.56578398, 4.80205189, 4.8038571 , 5.01190116, 5.01056863,
       4.9424992 ])

In [ ]:
np.mean(price_array)

157.56166666666667

In [ ]:
print(np.std(price_array))

47.83925285671681


In [ ]:
print(np.sum(price_array))

945.37


In [ ]:
print(np.max(price_array))

261.33


**Pandas**

In [ ]:
import pandas as pd

In [ ]:
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price)
print(s)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
dtype: float64


In [ ]:
price = [261.33, 121.76, 121.98, 150.19, 149.99, 140.12]
s = pd.Series(price)
print(s)

0    261.33
1    121.76
2    121.98
3    150.19
4    149.99
5    140.12
dtype: float64


In [ ]:
s = pd.Series(price, index = ['a', 'b', 'c', 'd', 'e', 'f'])
print(s)

a    143.73
b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64


In [ ]:
s = pd.Series(price, index = ['a', 'b', 'c', 'd', 'e', 'f'])
print(s)

a    261.33
b    121.76
c    121.98
d    150.19
e    149.99
f    140.12
dtype: float64


In [ ]:
s.index = [6,5,4,3,2,1]
print(s)

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64


In [ ]:
s.index = [6,5,4,3,2,1]
print(s)

6    261.33
5    121.76
4    121.98
3    150.19
2    149.99
1    140.12
dtype: float64


In [ ]:
print(s[1:])
print(s[:-2])


5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64
6    143.73
5    145.83
4    143.68
3    144.02
dtype: float64


In [ ]:
print(s[1:])
print(s[:-3])

5    121.76
4    121.98
3    150.19
2    149.99
1    140.12
dtype: float64
6    261.33
5    121.76
4    121.98
3    150.19
dtype: float64


In [ ]:
print(s[4])
s[4] = 0
print(s)

143.68
6    143.73
5    145.83
4      0.00
3      0.00
2    143.50
1    142.62
dtype: float64


In [ ]:
print(s[3])
s[3] = 0
print(s)

144.02
6    143.73
5    145.83
4    143.68
3      0.00
2    143.50
1    142.62
dtype: float64


In [ ]:
s = pd.Series(price, name = 'Apple Prices')
print(s)
print(s.name)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
Name: Apple Prices, dtype: float64
Apple Prices


In [ ]:
s = pd.Series(price, name = 'Carrot Prices')
print(s)
print(s.name)

0    261.33
1    121.76
2    121.98
3    150.19
4    149.99
5    140.12
Name: Carrot Prices, dtype: float64
Carrot Prices


In [ ]:
print(s.describe())

count      6.000000
mean     143.896667
std        1.059711
min      142.620000
25%      143.545000
50%      143.705000
75%      143.947500
max      145.830000
Name: Apple Prices, dtype: float64


In [ ]:
print(s.describe())

count      6.000000
mean     157.561667
std       52.405276
min      121.760000
25%      126.515000
50%      145.055000
75%      150.140000
max      261.330000
Name: Carrot Prices, dtype: float64


In [ ]:
time_index = pd.date_range('2017-01-01', periods = len(s), freq = 'D')
print(time_index)
s.index = time_index
print(s)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06'],
              dtype='datetime64[ns]', freq='D')
2017-01-01    143.73
2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
2017-01-06    142.62
Freq: D, Name: Apple Prices, dtype: float64


In [ ]:
time_index = pd.date_range('2018-12-09', periods = len(s), freq = 'D')
print(time_index)
s.index = time_index
print(s)

DatetimeIndex(['2018-12-09', '2018-12-10', '2018-12-11', '2018-12-12',
               '2018-12-13', '2018-12-14'],
              dtype='datetime64[ns]', freq='D')
2018-12-09    261.33
2018-12-10    121.76
2018-12-11    121.98
2018-12-12    150.19
2018-12-13    149.99
2018-12-14    140.12
Freq: D, Name: Carrot Prices, dtype: float64


In [ ]:
s.index = [6,5,4,3,2,1]
print(s)
print(s[1])

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
Name: Apple Prices, dtype: float64
142.62


In [ ]:
s.index = [7,6,5,4,3,2]
print(s)
print(s[2])

7    143.73
6    145.83
5    143.68
4    144.02
3    143.50
2    142.62
Name: Apple Prices, dtype: float64
142.62


In [ ]:
print(s.iloc[1])

145.83


In [ ]:
print(s.iloc[2])

143.68


In [ ]:
s.index = time_index
print(s['2017-01-03'])

143.68


In [ ]:
s.index = time_index
print(s['2018-12-09'])

261.33


In [ ]:
print(s['2017-01-02':'2017-01-05'])

2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
Freq: D, Name: Apple Prices, dtype: float64


In [ ]:
print(s['2020-06-07':'2020-07-05'])

Series([], Freq: D, Name: Carrot Prices, dtype: float64)


In [ ]:
print(s[s < np.mean(s)])
print(s[(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

2018-12-10    121.76
2018-12-11    121.98
2018-12-12    150.19
2018-12-13    149.99
2018-12-14    140.12
Freq: D, Name: Carrot Prices, dtype: float64
Series([], Freq: D, Name: Carrot Prices, dtype: float64)
